#!/bin/bash
# 수동 이미지 다운로드 스크립트
# 이 스크립트는 Unsplash API 키가 없을 때 사용합니다

echo "🌍 도시 이미지 수동 다운로드 가이드"
echo "=================================="
echo ""

# city 폴더 생성
mkdir -p public/city

echo "📥 다음 도시들의 이미지를 수동으로 다운로드하세요:"
echo ""

echo "🏙️  방콕 (bangkok)"
echo "   검색어: bangkok thailand city"
echo "   저장할 파일명: public/city/bangkok.jpg"
echo "   권장 크기: 300x200 픽셀"
echo ""
echo "🏙️  리스본 (lisbon)"
echo "   검색어: lisbon portugal city"
echo "   저장할 파일명: public/city/lisbon.jpg"
echo "   권장 크기: 300x200 픽셀"
echo ""
echo "🏙️  멕시코시티 (mexico-city)"
echo "   검색어: mexico city architecture"
echo "   저장할 파일명: public/city/mexico-city.jpg"
echo "   권장 크기: 300x200 픽셀"
echo ""
echo "🏙️  케이프타운 (cape-town)"
echo "   검색어: cape town south africa city"
echo "   저장할 파일명: public/city/cape-town.jpg"
echo "   권장 크기: 300x200 픽셀"
echo ""
echo "🏙️  부에노스아이레스 (buenos-aires)"
echo "   검색어: buenos aires argentina city"
echo "   저장할 파일명: public/city/buenos-aires.jpg"
echo "   권장 크기: 300x200 픽셀"
echo ""
echo "🏙️  두바이 (dubai)"
echo "   검색어: dubai uae city skyline"
echo "   저장할 파일명: public/city/dubai.jpg"
echo "   권장 크기: 300x200 픽셀"
echo ""
echo "🏙️  시드니 (sydney)"
echo "   검색어: sydney australia city harbor"
echo "   저장할 파일명: public/city/sydney.jpg"
echo "   권장 크기: 300x200 픽셀"
echo ""
echo "🏙️  발리 (bali)"
echo "   검색어: bali indonesia landscape"
echo "   저장할 파일명: public/city/bali.jpg"
echo "   권장 크기: 300x200 픽셀"
echo ""
echo "🏙️  베를린 (berlin)"
echo "   검색어: berlin germany city architecture"
echo "   저장할 파일명: public/city/berlin.jpg"
echo "   권장 크기: 300x200 픽셀"
echo ""
echo "🏙️  도쿄 (tokyo)"
echo "   검색어: tokyo japan city skyline"
echo "   저장할 파일명: public/city/tokyo.jpg"
echo "   권장 크기: 300x200 픽셀"
echo ""
echo "📝 다운로드 후 app/page.tsx에서 이미지 경로를 업데이트하세요:"
echo "   image: '/city/도시id.jpg'"
echo ""
echo "✅ 완료!"
